[package]
name = "campfire"
version = { workspace = true }
edition = "2021"
publish = false

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
toml_edit = { workspace = true }
itertools = { workspace = true }
toml = { workspace = true }

regex = "1.5.4"
rustdoc-json = "0.8.0"
rustdoc-types = "0.20.0"
simplelog = "0.12.1"
cargo_toml = "0.15"
guppy = "0.15"
indicatif = "0.17.3"
tokio = { version = "1.0", features = [
    "fs",
    "macros",
    "parking_lot",
    "process",
    "rt",
] }
futures = "0.3"
num_cpus = "1.15.0"
