[workspace]
default-members = ["app"]
exclude = ["guest", "tmp", "web"]
members = ["crates/*", "libs/*", "shared_crates/*", "app", "campfire"]
resolver = "2"

[workspace.package]
version = "0.3.0-dev"
rust-version = "1.67.0"

[workspace.dependencies]
aho-corasick = "0.7.20"
ambient_profiling = { version = "1.0.9", features = ["profile-with-puffin"] }
tracing = "0.1.35"
# tracing-tree = { version = "0.2" }
# https://github.com/davidbarsky/tracing-tree/pull/56#issuecomment-1489148431
tracing-tree = { git = "https://github.com/TmLev/tracing-tree" }
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
tracing-log = { version = "0.1" }
wgpu = { version = "0.16.0", features = ["serde", "trace", "replay"] }
winit = { version = "0.28.1", features = ["serde"] }
futures = { version = "0.3", default-features = false, features = ["std"] }
tokio = { version = "1.20", features = ["parking_lot"] }
bytemuck = { version = "1.10", features = ["derive"] }
glam = { version = "0.24", features = ["bytemuck", "serde", "rand"] }
gltf = "1.1.0"
ordered-float = { version = "3.4.0", features = ["serde"] }
derive_more = "0.99.11"
image = "0.24.5"
image_hasher = "1.1.2"
itertools = "0.10.3"
ndarray = { version = "0.15.3", features = ["serde"] }
rand = "0.8.0"
rand_pcg = "0.3.1"
glyph_brush = "0.7.4"
log = "0.4"
dyn-clonable = "0.9.0"
paste = "1.0"
as-any = "0.2.0"
closure = "0.3.0"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_bytes = "0.11.5"
serde_json = "1.0"
byteorder = "1.4.3"
bincode = "1.3.3"
lazy_static = "1.4.0"
strum = { version = "0.24", features = ["derive"] }
derivative = "2.2.0"
async-trait = "0.1.56"
png = "0.17.2"
puffin = "0.14.3"
futures-signals = "0.3"
open = "2.0.2"
which = "4.3.0"
puffin_http = "0.11.1"
fbxcel = { version = "0.9.0", features = ["tree"] }
reqwest = { version = "0.11.11", default-features = false, features = [
    'blocking',
    'rustls-tls',
    'json',
] }
url = { version = "2", features = ["serde"] }
thiserror = "1.0"
thread-priority = "0.10.0"
once_cell = "1.13.0"
smallvec = "1.8.0"
downcast-rs = "1.2.0"
yaml-rust = { version = "0.5", package = "yaml-rust-davvid" }
maplit = "1.0.2"
chrono = { version = "0.4", default-features = false, features = [
    "serde",
    "clock",
] }
manual_future = "0.1.1"
base64 = "0.13.0"
env_logger = "0.10.0"
async-recursion = "1.0.0"
anyhow = { version = "1.0", features = ["backtrace"] }
bitflags = "1.3"
quinn = { version = "0.10", features = ["futures-io"] }
rustls = { version = "0.21", features = ["dangerous_configuration", "quic"] }
rustls-pemfile = "1.0"
parking_lot = { version = "0.12.0", features = ["serde"] }
clap = { version = "4.0", features = ["derive"] }
sentry = { version = "0.27.0", default-features = false, features = [
    'backtrace',
    'contexts',
    'panic',
    'debug-images',
    'reqwest',
    'rustls',
    'anyhow',
] }
sentry-contrib-breakpad = "0.5.0"
sentry-log = "0.27.0"
sentry-contrib-native = { version = "0.3.1" }
sentry-anyhow = "0.27.0"
enumflags2 = "0.6"
num-traits = "0.2"
num-derive = "0.3"
proc-macro2 = "1.0"
quote = "1.0"
pretty_assertions = "1.2.1"
syn = { version = "1.0", features = ["full", "extra-traits"] }
proc-macro-crate = "1.1.0"
bytes = { version = "1.1.0", features = ["serde"] }
dashmap = "5.3.0"
slotmap = "1.0.6"
atomic_refcell = "0.1.8"
flume = { version = "0.10", features = ["async"] }
im = "15.1.0"
axum = "0.6.4"
tower-http = { version = "0.3.0", features = ["cors", "fs"] }
tower = "0.4.13"
indexmap = { version = "1.8.2", features = ["serde"] }
fixed-vec-deque = "0.1.9"
hex = "0.4.3"
ring = "0.16.20"
data-encoding = "2.3.2"
convert_case = "0.6.0"
fs_extra = "1.2.0"
slugify = "0.1.0"
serde_yaml = "0.9.17"
bit-set = "0.5.3"
bit-vec = "0.6.3"
glob = "0.3.0"
walkdir = "2"
relative-path = { version = "1.7", features = ["serde"] }
pin-project = "1.0"
abort-on-drop = "0.2"
toml = "0.7.1"
percent-encoding = "2.2.0"
indoc = "2.0"
local-ip-address = "0.5.1"
cargo_toml = "0.15.0"
git-version = "0.3.5"
toml_edit = "0.19.3"
arboard = "3.2.0"
noise = { version = "0.7.0", default-features = false }
russimp = { version = "1.0.6", features = ['prebuilt'] }
symphonia = { version = "0.5", default-features = false, features = [
    "mp3",
    "pcm",
    "wav",
] }
vorbis_rs = "0.3.0"
colored = "2.0.0"
directories = "5.0.1"
ulid = { version = "1.0.0", features = ["serde"] }
enum_dispatch = "0.3"
uuid = "1.3"
scopeguard = "1.0"
rustls-native-certs = "0.6.2"
webpki-roots = "0.23.0"
mikktspace = { git = "https://github.com/gltf-rs/mikktspace" }

#
# WASM dependencies. Should be able to move off these once this all begins to stabilise a little.
#

wasmtime = { version = "8.0.1", features = ["component-model"] }
# Use published versions of these crates when available, or pull them in ourselves
wasmtime-wasi = { package = "host", git = "https://github.com/AmbientRun/preview2-prototyping.git", branch = "sync" }
wasi-cap-std-sync = { git = "https://github.com/AmbientRun/preview2-prototyping.git", branch = "sync" }
wasi-common = { git = "https://github.com/AmbientRun/preview2-prototyping.git", branch = "sync" }
wit-bindgen-core = "0.6.0"
wit-bindgen-rust = "0.6.0"
wit-component = "0.8.1"
