
[components."core::physics"]
name = "Physics"
description = "Physics functionality and state."

[components."core::physics::angular_velocity"]
type = "Vec3"
name = "Angular velocity"
description = """
Angular velocity (radians/second) of this entity in the physics scene.
Updating this component will update the entity's angular velocity in the physics scene."""
attributes = ["Debuggable", "Networked", "Store"]

[components."core::physics::cube_collider"]
type = "Vec3"
name = "Cube collider"
description = """
If attached, this entity will have a cube physics collider.
`x, y, z` is the size of the cube."""
attributes = ["Debuggable", "Networked", "Store"]

[components."core::physics::character_controller_height"]
type = "F32"
name = "Character controller height"
description = """
The height of the physics character controller attached to this entity.
If an entity has both this and a `character_controller_radius`, it will be given a physical character collider."""
attributes = ["Debuggable", "Networked", "Store"]

[components."core::physics::character_controller_radius"]
type = "F32"
name = "Character controller radius"
description = """
The radius of the physics character controller attached to this entity.
If an entity has both this and a `character_controller_height`, it will be given a physical character collider."""
attributes = ["Debuggable", "Networked", "Store"]

[components."core::physics::collider_from_url"]
type = "String"
name = "Collider from URL"
description = """
This entity will load its physics collider from the URL.
The value is the URL to load from."""
attributes = ["Debuggable", "Networked", "Store"]

[components."core::physics::collider_loaded"]
type = "Empty"
name = "Collider loaded"
description = """
This component is automatically attached to an entity once the collider has been loaded (through e.g. `collider_from_url`)."""
attributes = ["Debuggable", "Networked", "Store"]

[components."core::physics::collider_loads"]
type = { type = "Vec", element_type = "EntityId" }
name = "Collider loads"
description = "Contains all colliders that were loaded in this physics tick."
attributes = ["Debuggable", "Networked", "Resource", "Store"]

[components."core::physics::contact_offset"]
type = "F32"
name = "Contact offset"
description = """
Contact offset (in meters) of this entity in the physics scene.
Updating this component will update the entity's contact offset for each attached shape in the physics scene."""
attributes = ["Debuggable", "Networked", "Store"]

[components."core::physics::density"]
type = "F32"
name = "Density"
description = """
The density of this entity.
This is used to update the `mass` when the entity is rescaled."""
default = 1.0
attributes = ["Debuggable", "Networked", "Store"]

[components."core::physics::dynamic"]
type = "Bool"
name = "Dynamic"
description = "If this is true, the entity will be dynamic (i.e. be able to move). Otherwise, it will be static."
attributes = ["Debuggable", "Networked", "Store"]

[components."core::physics::kinematic"]
type = "Empty"
name = "Kinematic"
description = "If attached, and this entity is dynamic, this entity will also be kinematic (i.e. unable to be affected by other entities motion). Otherwise, it will receive forces normally."
attributes = ["Debuggable", "Networked", "Store"]

[components."core::physics::linear_velocity"]
type = "Vec3"
name = "Linear velocity"
description = """
Linear velocity (meters/second) of this entity in the physics scene.
Updating this component will update the entity's linear velocity in the physics scene."""
attributes = ["Debuggable", "Networked", "Store"]

[components."core::physics::make_physics_static"]
type = "Bool"
name = "Make physics static"
description = "All physics objects will be made static when loaded."
attributes = ["Debuggable", "Networked", "Resource", "Store"]

[components."core::physics::mass"]
type = "F32"
name = "Mass"
description = "The mass of this entity, measured in kilograms."
default = 1.0
attributes = ["Debuggable", "Networked", "Store"]

[components."core::physics::physics_controlled"]
type = "Empty"
name = "Physics controlled"
description = """
If attached, this entity will be controlled by physics.
Note that this requires the entity to have a collider."""
attributes = ["Debuggable", "Networked", "Store"]

[components."core::physics::plane_collider"]
type = "Empty"
name = "Plane collider"
description = "If attached, this entity will have a plane physics collider."
attributes = ["Debuggable", "Networked", "Store"]

[components."core::physics::rest_offset"]
type = "F32"
name = "Rest offset"
description = """
Rest offset (in meters) of this entity in the physics scene.
Updating this component will update the entity's rest offset for each attached shape in the physics scene."""
attributes = ["Debuggable", "Networked", "Store"]

[components."core::physics::sphere_collider"]
type = "F32"
name = "Sphere collider"
description = """
If attached, this entity will have a sphere physics collider.
The value corresponds to the radius of the sphere."""
attributes = ["Debuggable", "Networked", "Store"]

[components."core::physics::unit_mass"]
type = "F32"
name = "Unit mass"
description = "The mass of a character/unit."
attributes = ["Debuggable", "Networked", "Store"]

[components."core::physics::unit_velocity"]
type = "Vec3"
name = "Unit velocity"
description = "The velocity of a character/unit."
attributes = ["Debuggable", "Networked", "Store"]

[components."core::physics::unit_yaw"]
type = "F32"
name = "Unit yaw"
description = "The yaw of a character/unit."
attributes = ["Debuggable", "Networked", "Store"]

[components."core::physics::visualize_collider"]
type = "Empty"
name = "Visualize collider"
description = "If attached, the collider will be rendered."
attributes = ["Debuggable", "Networked"]
