[workspace]
members = ["api", "api_core", "api_core/api_macros", "examples/*/*"]

[workspace.package]
rust-version = "1.67.0"
version = "0.3.0-dev"

[workspace.dependencies]
ambient_api = { path = "api", version = "0.3.0-dev" }
ambient_api_core = { path = "api_core", version = "0.3.0-dev" }
ambient_api_macros = { path = "api_core/api_macros", version = "0.3.0-dev" }

ambient_project = { path = "../../shared_crates/project", version = "0.3.0-dev" }
ambient_project_macro_common = { path = "../../shared_crates/project_macro_common", version = "0.3.0-dev" }
ambient_project_rt = { path = "../../shared_crates/project_rt", version = "0.3.0-dev" }
ambient_shared_types = { path = "../../shared_crates/shared_types", version = "0.3.0-dev" }
ambient_ui = { path = "../../shared_crates/ui", version = "0.3.0-dev", features = [
    "guest",
] }
ambient_element = { path = "../../shared_crates/element", version = "0.3.0-dev", default-features = false, features = [
    "guest",
] }
ambient_editor_derive = { path = "../../shared_crates/editor_derive", version = "0.3.0-dev" }
ambient_schema = { path = "../../shared_crates/schema", version = "0.3.0-dev" }

ambient_friendly_id = { path = "../../libs/friendly_id", version = "0.3.0-dev" }
ambient_cb = { path = "../../libs/cb", version = "0.3.0-dev" }

anyhow = "1.0"
byteorder = "1.4"
data-encoding = "2.3.3"
futures = "0.3"
glam = { version = "0.22.0", features = ["rand"] }
once_cell = "1.15.0"
paste = "1.0"
thiserror = "1.0"
rand = "0.8.5"
wit-bindgen = { version = "0.6.0", features = ["realloc"] }
ulid = { version = "1.0.0", features = ["serde"] }
static_assertions = "1.1.0"
