[workspace]
members = [
    "api",
    "api_core",
    "api_core/api_macros",
    # Basics
    "examples/advanced/forest",
    "examples/basics/asset_loading",
    "examples/basics/async",
    "examples/basics/clientside",
    "examples/basics/decals",
    "examples/basics/first_person_camera",
    "examples/basics/fog",
    "examples/basics/image",
    "examples/basics/input",
    "examples/basics/messaging",
    "examples/basics/multiplayer",
    "examples/basics/physics",
    "examples/basics/primitives",
    "examples/basics/procedural_generation",
    "examples/basics/raw_text",
    "examples/basics/samplers",
    "examples/basics/screen_ray",
    "examples/basics/skinmesh",
    "examples/basics/sun",
    "examples/basics/third_person_camera",
    "examples/basics/transparency",
    # UI
    "examples/ui/auto_editor",
    "examples/ui/button",
    "examples/ui/counter",
    "examples/ui/dock_layout",
    "examples/ui/editors",
    "examples/ui/flow_layout",
    "examples/ui/image",
    "examples/ui/rect",
    "examples/ui/screens",
    "examples/ui/slider",
    "examples/ui/text",
    "examples/ui/todo",
    # Games
    "examples/games/minigolf",
    "examples/games/music_sequencer",
    "examples/games/pong",
    "examples/games/tictactoe",
]

[workspace.package]
rust-version = "1.67.0"
version = "0.3.0-dev"

[workspace.dependencies]
ambient_api = { path = "api", version = "0.3.0-dev" }
ambient_api_core = { path = "api_core", version = "0.3.0-dev" }
ambient_api_macros = { path = "api_core/api_macros", version = "0.3.0-dev" }

ambient_project = { path = "../../shared_crates/project", version = "0.3.0-dev" }
ambient_project_macro_common = { path = "../../shared_crates/project_macro_common", version = "0.3.0-dev" }
ambient_project_rt = { path = "../../shared_crates/project_rt", version = "0.3.0-dev" }
ambient_shared_types = { path = "../../shared_crates/shared_types", version = "0.3.0-dev" }
ambient_ui = { path = "../../shared_crates/ui", version = "0.3.0-dev", features = [
    "guest",
] }
ambient_element = { path = "../../shared_crates/element", version = "0.3.0-dev", default-features = false, features = [
    "guest",
] }
ambient_editor_derive = { path = "../../shared_crates/editor_derive", version = "0.3.0-dev" }
ambient_schema = { path = "../../shared_crates/schema", version = "0.3.0-dev" }

ambient_friendly_id = { path = "../../libs/friendly_id", version = "0.3.0-dev" }
ambient_cb = { path = "../../libs/cb", version = "0.3.0-dev" }

anyhow = "1.0"
byteorder = "1.4"
data-encoding = "2.3.3"
futures = "0.3"
glam = { version = "0.24.0", features = ["rand"] }
once_cell = "1.15.0"
paste = "1.0"
thiserror = "1.0"
rand = "0.8.5"
wit-bindgen = { version = "0.6.0", features = ["realloc"] }
ulid = { version = "1.0.0", features = ["serde"] }
static_assertions = "1.1.0"
