[ember]
id = "ambient_example_input"
name = "input"
version = "0.0.1"
repository = "https://github.com/AmbientRun/Ambient/tree/main/guest/rust/examples/basics/input"
type = "Game"
categories = ["Example"]
