
[package]
name = "ambient_world_audio"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"
description = "Ambient world audio. Host-only."
license = "MIT OR Apache-2.0"
repository = "https://github.com/AmbientRun/Ambient"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambient_sys = { path = "../sys" , version = "0.3.0-dev" }
ambient_ecs = { path = "../ecs" , version = "0.3.0-dev" }
ambient_app = { path = "../app" , version = "0.3.0-dev" }
ambient_ui_native = { path = "../ui_native" , version = "0.3.0-dev" }
ambient_core = { path = "../core" , version = "0.3.0-dev" }
ambient_element = { path = "../../shared_crates/element" , version = "0.3.0-dev" }
ambient_std = { path = "../std" , version = "0.3.0-dev" }
ambient_audio = { path = "../audio" , version = "0.3.0-dev" }
# ambient_network = { path = "../network" , version = "0.2.1" }
parking_lot = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
dashmap = { workspace = true }
slotmap = { workspace = true }
thiserror = { workspace = true }
flume = { workspace = true }
futures = { workspace = true }
indexmap = { workspace = true }
once_cell = { workspace = true }
rand = { workspace = true }
rand_chacha = "0.3.1"
itertools = { workspace = true }
closure = { workspace = true }
glam = { workspace = true }
ordered-float = { workspace = true }
ambient_profiling = { workspace = true }
atomic_refcell = "0.1.8"
tracing = { workspace = true }
derive_more = { workspace = true }

[dev-dependencies]
tracing-subscriber = { workspace = true }
ambient_renderer = { path = "../renderer" }
ambient_primitives = { path = "../primitives" }
ambient_cameras = { path = "../cameras" }

[features]
hotload-includes = ['ambient_std/hotload-includes']
