[ember]
id = "ambient_example_messaging"
name = "Messaging"
version = "0.0.1"
repository = "https://github.com/AmbientRun/Ambient/tree/main/guest/rust/examples/basics/messaging"
type = "Game"
categories = ["Example"]

[messages.hello]
name = "Hello"
description = "Sent when a client joins the server, then sent back from the server"
fields = { text = "String", source_reliable = "Bool" }
# see all the supported types here:
# https://ambientrun.github.io/Ambient/reference/project.html#components--components

[messages.local]
description = "Sent until it's acknowledged"
fields = { text = "String" }
