[package]
name = "ambient_gizmos"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"
description = "Ambient gizmos. Host-only."
license = "MIT OR Apache-2.0"
repository = "https://github.com/AmbientRun/Ambient"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambient_std = { path = "../std" , version = "0.3.0-dev" }
ambient_ecs = { path = "../ecs" , version = "0.3.0-dev" }
ambient_gpu = { path = "../gpu" , version = "0.3.0-dev" }
ambient_core = { path = "../core" , version = "0.3.0-dev" }
ambient_meshes = { path = "../meshes" , version = "0.3.0-dev" }
ambient_renderer = { path = "../renderer" , version = "0.3.0-dev" }
dashmap = { workspace = true }
glam = { workspace = true }
bytemuck = { workspace = true }
wgpu = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
once_cell = "1.13.0"
ambient_profiling = { workspace = true }

[dev-dependencies]
ambient_app = { path = "../app" }
ambient_cameras = { path = "../cameras" }

[features]
hotload-includes = ['ambient_std/hotload-includes']
