
[package]
name = "ambient_physics"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"
description = "Ambient physics. Host-only."
license = "MIT OR Apache-2.0"
repository = "https://github.com/AmbientRun/Ambient"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambient_ecs = { path = "../ecs", version = "0.3.0-dev" }
ambient_std = { path = "../std", version = "0.3.0-dev" }
ambient_core = { path = "../core", version = "0.3.0-dev" }
ambient_meshes = { path = "../meshes", version = "0.3.0-dev" }
ambient_network = { path = "../network", version = "0.3.0-dev" }
ambient_gizmos = { path = "../gizmos", version = "0.3.0-dev" }
ambient_model = { path = "../model", version = "0.3.0-dev" }
ambient_primitives = { path = "../primitives", version = "0.3.0-dev" }

physxx = { path = "../../libs/physxx", version = "0.3.0-dev" }
serde = { workspace = true }
serde_json = { workspace = true }
glam = { workspace = true }
itertools = { workspace = true }
futures = { workspace = true }
rand = { workspace = true }
async-trait = { workspace = true }
parking_lot = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
ambient_profiling = { workspace = true }
ordered-float = { workspace = true }
once_cell = { workspace = true }
tokio = { workspace = true }
log = { workspace = true }

[dev-dependencies]
ambient_app = { path = "../app" }
ambient_renderer = { path = "../renderer" }
ambient_primitives = { path = "../primitives" }
ambient_cameras = { path = "../cameras" }
ambient_element = { path = "../../shared_crates/element" }
