[package]
name = "ambient_prefab"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"
description = "Ambient entity prefab implementation. Host-only."
license = "MIT OR Apache-2.0"
repository = "https://github.com/AmbientRun/Ambient"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambient_ecs = { path = "../ecs", version = "0.3.0-dev" }
ambient_core = { path = "../core", version = "0.3.0-dev" }
ambient_model = { path = "../model", version = "0.3.0-dev" }
ambient_network = { path = "../network", version = "0.3.0-dev" }
ambient_physics = { path = "../physics", version = "0.3.0-dev" }
ambient_rpc = { path = "../rpc", version = "0.3.0-dev" }
ambient_std = { path = "../std", version = "0.3.0-dev" }
ambient_decals = { path = "../decals", version = "0.3.0-dev" }
glam = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
log = { workspace = true }
serde_json = { workspace = true }
