[package]
name = "ambient_procedurals"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"
description = "Ambient procedural generation functionality."
license = "MIT OR Apache-2.0"
repository = "https://github.com/AmbientRun/Ambient"

[dependencies]
ambient_std = { path = "../std" , version = "0.3.0-dev" }
ambient_core = { path = "../core" , version = "0.3.0-dev" }
ambient_ecs = { path = "../ecs" , version = "0.3.0-dev" }
ambient_gpu = { path = "../gpu" , version = "0.3.0-dev" }
ambient_renderer = { path = "../renderer" , version = "0.3.0-dev" }
ambient_shared_types = { path = "../../shared_crates/shared_types" , version = "0.3.0-dev" }

parking_lot = { workspace = true }
ulid = { workspace = true }
tracing = { workspace = true }
wgpu = { workspace = true }
paste = { workspace = true }
