[package]
name = "ambient_ui_native"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"
description = "Ambient UI native host functionality. Host-only."
license = "MIT OR Apache-2.0"
repository = "https://github.com/AmbientRun/Ambient"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambient_sys = { path = "../sys" , version = "0.3.0-dev" }
ambient_std = { path = "../std" , version = "0.3.0-dev" }
ambient_ecs = { path = "../ecs" , version = "0.3.0-dev" }
ambient_gpu = { path = "../gpu" , version = "0.3.0-dev" }
ambient_core = { path = "../core" , version = "0.3.0-dev" }
ambient_meshes = { path = "../meshes" , version = "0.3.0-dev" }
ambient_input = { path = "../input" , version = "0.3.0-dev" }
ambient_renderer = { path = "../renderer" , version = "0.3.0-dev" }
ambient_layout = { path = "../layout" , version = "0.3.0-dev" }
ambient_text = { path = "../text" , version = "0.3.0-dev" }
ambient_rect = { path = "../rect" , version = "0.3.0-dev" }
ambient_cb = { path = "../../libs/cb" , version = "0.3.0-dev" }
ambient_element = { path = "../../shared_crates/element" , version = "0.3.0-dev" }
ambient_ui = { path = "../../shared_crates/ui", default-features = false, features = ["native"] , version = "0.3.0-dev" }
ambient_editor_derive = { path = "../../shared_crates/editor_derive" , version = "0.3.0-dev" }
ambient_shared_types = { path = "../../shared_crates/shared_types", features = ["native"] , version = "0.3.0-dev" }
glam = { workspace = true }
winit = { workspace = true }
itertools = { workspace = true }
futures = { workspace = true }
closure = { workspace = true }
log = { workspace = true }
wgpu = { workspace = true }
indexmap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
parking_lot = { workspace = true }
thiserror = { workspace = true }
ordered-float = { workspace = true }
tokio = { workspace = true }
bytemuck = { workspace = true }
convert_case = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
ambient_app = { path = "../app" }
ambient_cameras = { path = "../cameras" }
fixed-vec-deque = { workspace = true }
tokio = { workspace = true }
itertools = { workspace = true }
rand = { workspace = true }
env_logger = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[features]
hotload-includes = ['ambient_std/hotload-includes']


[target.'cfg(not(target_os = "unknown"))'.dependencies]
arboard = { workspace = true }
