[ember]
id = "ambient_example_samplers"
name = "samplers"
version = "0.0.1"
repository = "https://github.com/AmbientRun/Ambient/tree/main/guest/rust/examples/basics/samplers"
type = "Game"
categories = ["Example"]
