[package]
name = "ambient_renderer"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"
description = "Ambient renderer. Host-only."
license = "MIT OR Apache-2.0"
repository = "https://github.com/AmbientRun/Ambient"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambient_sys = { path = "../sys" , version = "0.3.0-dev" }
ambient_std = { path = "../std" , version = "0.3.0-dev" }
ambient_ecs = { path = "../ecs" , version = "0.3.0-dev" }
ambient_gpu = { path = "../gpu" , version = "0.3.0-dev" }
ambient_core = { path = "../core" , version = "0.3.0-dev" }
ambient_meshes = { path = "../meshes" , version = "0.3.0-dev" }
ambient_color = { path = "../../libs/color", features = ["wgpu"] , version = "0.3.0-dev" }
wgpu = { workspace = true }
glam = { workspace = true }
itertools = { workspace = true }
ordered-float = { workspace = true }
serde = { workspace = true }
derive_more = { workspace = true }
downcast-rs = { workspace = true }
ambient_profiling = { workspace = true }
bytemuck = { workspace = true }
smallvec = { workspace = true }
log = { workspace = true }
parking_lot = { workspace = true }
async-trait = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
ulid = { workspace = true }

[dev-dependencies]
ambient_app = { path = "../app" }
ambient_element = { path = "../../shared_crates/element" }
ambient_gizmos = { path = "../gizmos" }
ambient_model_import = { path = "../model_import" }
ambient_cameras = { path = "../cameras" }
ambient_primitives = { path = "../primitives" }
env_logger = { workspace = true }
winit = { workspace = true }
tracing-subscriber = { workspace = true }

[features]
hotload-includes = ['ambient_std/hotload-includes']
