[package]
name = "ambient_project_macro"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"
description = "Ambient internal host project macro. Host-only."
license = "MIT OR Apache-2.0"
repository = "https://github.com/AmbientRun/Ambient"

[lib]
proc-macro = true

[dependencies]
ambient_project_macro_common = { path = "../../shared_crates/project_macro_common" , version = "0.3.0-dev" }
ambient_schema = { path = "../../shared_crates/schema" , version = "0.3.0-dev" }
syn = { workspace = true }
proc-macro2 = { workspace = true }
