[ember]
id = "runtime_components"
name = "Runtime Components"
version = "0.3.0-dev"

includes = [
    "schema/animation.toml",
    "schema/app_.toml",
    "schema/audio.toml",
    "schema/camera.toml",
    "schema/ecs.toml",
    "schema/input.toml",
    "schema/layout.toml",
    "schema/model.toml",
    "schema/network.toml",
    "schema/physics.toml",
    "schema/player.toml",
    "schema/prefab.toml",
    "schema/primitives.toml",
    "schema/procedurals.toml",
    "schema/rect.toml",
    "schema/rendering.toml",
    "schema/text.toml",
    "schema/transform.toml"
]

# Components

[components.core]
name = "Core"
description = "Contains all core components for the Ambient runtime."

[components."core::game_objects"]
name = "Game Objects"
description = "Pre-defined game objects that implement specific behaviours."

[components."core::wasm"]
name = "WASM"
description = "Internal implementation details of WASM integration."


# Messages
[messages.frame]
name = "Frame"
description = "Sent to all modules every frame."
fields = {}

[messages.collision]
name = "Collision"
description = "Sent when a collision occurs."
fields = { ids = { container_type = "Vec", element_type = "EntityId" } }

[messages.collider_loads]
name = "Collider Loads"
description = "Sent when colliders load."
fields = { ids = { container_type = "Vec", element_type = "EntityId" } }

[messages.module_load]
name = "Module Load"
description = "Sent to a module when it loads."
fields = {}

[messages.module_unload]
name = "Module Unload"
description = "Sent to a module when it unloads."
fields = {}

[messages.window_focus_change]
name = "Window Focus Change"
description = "Sent when the window gains or loses focus."
fields = { focused = "Bool" }

[messages.window_close]
name = "Window Close"
description = "Sent when the window is closed."
fields = {}

[messages.window_keyboard_character]
name = "Window Keyboard Character"
description = "Sent when the window receives a character from the keyboard."
fields = { character = "String" }

[messages.window_keyboard_modifiers_change]
name = "Window Keyboard Modifiers Change"
description = "Sent when the window's keyboard modifiers change."
fields = { modifiers = "U32" }

[messages.window_keyboard_input]
name = "Window Keyboard Input"
description = "Sent when the window receives a keyboard input."
fields = { pressed = "Bool", modifiers = "U32", keycode = { type = "Option", element_type = "String" } }

[messages.window_mouse_input]
name = "Window Mouse Input"
description = "Sent when the window receives a mouse input."
fields = { pressed = "Bool", button = "U32" }

[messages.window_mouse_wheel]
name = "Window Mouse Wheel"
description = "Sent when the window receives a mouse wheel input."
fields = { delta = "Vec2", pixels = "Bool" }

[messages.window_mouse_motion]
name = "Window Mouse Motion"
description = "Sent when the window receives a mouse motion input."
fields = { delta = "Vec2" }
