[package]
name = "ambient_project_macro_common"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"
description = "Common implementation of a proc-macro that generates boilerplate from an `ambient.toml`."
license = "MIT OR Apache-2.0"
repository = "https://github.com/AmbientRun/Ambient"

[dependencies]
anyhow = { workspace = true }
quote = { workspace = true }
serde = { workspace = true }
syn = { workspace = true }
thiserror = { workspace = true }
toml = { workspace = true }
proc-macro2 = { workspace = true }

ambient_project = { path = "../project" , version = "0.3.0-dev" }
ambient_shared_types = { path = "../shared_types" , version = "0.3.0-dev" }

[dev-dependencies]
indoc = "2.0"
