[ember]
id = "ambient_example_primitives"
name = "Primitives"
version = "0.0.1"
repository = "https://github.com/AmbientRun/Ambient/tree/main/guest/rust/examples/basics/primitives"
type = "Game"
categories = ["Example"]