[ember]
id = "ambient_example_scroll"
name = "Scroll"
version = "0.0.1"
repository = "https://github.com/AmbientRun/Ambient/tree/main/guest/rust/examples/ui/scroll"
type = "Game"
categories = ["Example"]
