[ember]
id = "ambient_example_todo"
name = "todo"
version = "0.0.1"
repository = "https://github.com/AmbientRun/Ambient/tree/main/guest/rust/examples/ui/todo"
type = "Game"
categories = ["Example"]

[messages.new_item]
description = "Add a new todo item"
fields = { description = "String" }

[messages.delete_item]
description = "Remove todo item"
fields = { id = "EntityId" }

[components.todo_item]
type = "String"
name = "Todo item"
description = "Item in the todo list."
attributes = ["Networked", "Debuggable"]

[components.todo_time]
type = "Duration"
name = "Todo time"
description = "The time the todo was created."
attributes = ["Networked", "Debuggable"]
