[ember]
id = "ambient_example_raw_text"
name = "Raw Text"
version = "0.0.1"
repository = "https://github.com/AmbientRun/Ambient/tree/main/guest/rust/examples/basics/raw_text"
type = "Game"
categories = ["Example"]
