[ember]
id = "ambient_example_third_person_camera"
name = "Third person camera"
version = "0.0.1"
repository = "https://github.com/AmbientRun/Ambient/tree/main/guest/rust/examples/basics/third_person_camera"
type = "Game"
categories = ["Example"]

[components]
player_camera_ref = { type = "EntityId", name = "Player camera ref", description = "The player's camera.", attributes = [
    "Debuggable",
] }
player_movement_direction = { type = "Vec2", name = "Player movement direction", description = "The player's movement direction.", attributes = [
    "Debuggable",
] }
player_mouse_delta_x = { type = "F32", name = "Player mouse delta X", description = "The player's mouse delta X.", attributes = [
    "Debuggable",
] }

camera_follow_distance = { type = "F32", name = "Camera follow distance", description = "The distance the camera follows the player.", attributes = [
    "Debuggable",
    "Networked",
] }

player_scroll = { type = "F32", name = "Player mouse scroll", description = "The player's mouse scroll.", attributes = [
    "Debuggable",
] }

[messages.input]
description = "Describes the input state of the player."

[messages.input.fields]
direction = { type = "Vec2", name = "Direction", description = "The movement direction of the player." }
mouse_delta_x = { type = "F32", name = "Mouse delta X", description = "The mouse delta X." }
scroll = { type = "F32", name = "Scroll", description = "The vertical scroll." }
