[package]
name = "ambient_project"
edition = "2021"
description = "Definition of the Ambient project manifest format."
license = "MIT OR Apache-2.0"
repository = "https://github.com/AmbientRun/Ambient"
rust-version = { workspace = true }
version = { workspace = true }

[dependencies]
quote = "1.0"
syn = "1.0"
proc-macro2 = "1.0"

serde = { workspace = true }
toml = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }

[dev-dependencies]
paste = { workspace = true }
serde_json = { workspace = true }
ambient_shared_types = { path = "../../shared_crates/shared_types" }
