[ember]
id = "ambient_example_tictactoe"
name = "Tic Tac Toe"
version = "0.0.1"
repository = "https://github.com/AmbientRun/Ambient/tree/main/guest/rust/examples/games/tictactoe"
type = "Game"
categories = ["Example"]

[components]
cells = { type = { type = "Vec", element_type = "EntityId" }, name = "Cells", description = "The cells in the game", attributes = [
    "Debuggable",
    "Networked",
] }
cell = { type = "I32", name = "Cell", description = "The ID of the cell this player is in", attributes = [
    "Debuggable",
    "Networked",
] }
owned_by = { type = "EntityId", name = "Owned By", description = "The ID of the player that owns this cell", attributes = [
    "Debuggable",
    "Networked",
] }

[messages.input]
description = "The player's input"
[messages.input.fields]
up = { type = "Bool", name = "Up", description = "Whether the player is pressing the up key" }
down = { type = "Bool", name = "Down", description = "Whether the player is pressing the down key" }
left = { type = "Bool", name = "Left", description = "Whether the player is pressing the left key" }
right = { type = "Bool", name = "Right", description = "Whether the player is pressing the right key" }
capture = { type = "Bool", name = "Capture", description = "Whether the player is pressing the capture key" }
