[package]
name = "ambient_model"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"
description = "Ambient model functionality. Host-only."
license = "MIT OR Apache-2.0"
repository = "https://github.com/AmbientRun/Ambient"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambient_sys = { path = "../sys" , version = "0.3.0-dev" }
ambient_std = { path = "../std" , version = "0.3.0-dev" }
ambient_core = { path = "../core" , version = "0.3.0-dev" }
ambient_ecs = { path = "../ecs" , version = "0.3.0-dev" }
ambient_renderer = { path = "../renderer" , version = "0.3.0-dev" }
ambient_meshes = { path = "../meshes" , version = "0.3.0-dev" }
ambient_gpu = { path = "../gpu" , version = "0.3.0-dev" }
ambient_editor_derive = { path = "../../shared_crates/editor_derive" , version = "0.3.0-dev" }
ambient_ui_native = { path = "../ui_native" , version = "0.3.0-dev" }
futures = { workspace = true }
glam = { workspace = true }
itertools = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }
wgpu = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
bytemuck = { workspace = true }
async-trait = { workspace = true }
url = { workspace = true }

[features]
hotload-includes = ['ambient_std/hotload-includes']
