[package]
name = "ambient_std"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"
description = "Ambient internal standard library. Host-only."
license = "MIT OR Apache-2.0"
repository = "https://github.com/AmbientRun/Ambient"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambient_asset_cache = { path = "../asset_cache/", optional = true, version = "0.3.0-dev" }
ambient_sys = { path = "../sys", version = "0.3.0-dev" }

ambient_cb = { path = "../../libs/cb", version = "0.3.0-dev" }
ambient_color = { path = "../../libs/color", version = "0.3.0-dev" }
ambient_friendly_id = { path = "../../libs/friendly_id", version = "0.3.0-dev" }
ambient_math = { path = "../../libs/math", version = "0.3.0-dev" }
anyhow = { workspace = true }
tracing = { workspace = true }
ulid = { workspace = true }
mikktspace = { workspace = true }

wgpu = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
glam = { workspace = true, optional = true }
ordered-float = { workspace = true, optional = true }
rand = { workspace = true, optional = true }
tokio = { workspace = true, optional = true, features = ["sync"] }
as-any = { workspace = true, optional = true }
async-trait = { workspace = true, optional = true }
futures = { workspace = true, optional = true }
itertools = { workspace = true, optional = true }
bytemuck = { workspace = true, optional = true }
log = { workspace = true, optional = true }
reqwest = { workspace = true, optional = true }
thiserror = { workspace = true, optional = true }
yaml-rust = { workspace = true, optional = true }
sentry-anyhow = { workspace = true, optional = true }
parking_lot = { workspace = true, optional = true }
ambient_profiling = { workspace = true, optional = true }
ring = { workspace = true, optional = true }
data-encoding = { workspace = true, optional = true }
chrono = { workspace = true, optional = true }
bincode = { workspace = true, optional = true }
convert_case = { workspace = true, optional = true }
once_cell = { workspace = true, optional = true }
pin-project = { workspace = true, optional = true }
url = { workspace = true, optional = true }
relative-path = { workspace = true, optional = true }
toml = { workspace = true, optional = true }
percent-encoding = { workspace = true, optional = true }

[features]
# This package was very quickly partitioned to allow its use in build scripts
# without dragging in all of its dependencies. If you have some free time, try
# splitting these up into finer-grained features!
default = ["all"]
all = ["uncategorized"]
uncategorized = [
    "dep:ambient_asset_cache",
    "dep:wgpu",
    "dep:serde",
    "dep:serde_json",
    "dep:glam",
    "dep:ordered-float",
    "dep:rand",
    "dep:tokio",
    "dep:as-any",
    "dep:async-trait",
    "dep:futures",
    "dep:itertools",
    "dep:bytemuck",
    "dep:log",
    "dep:reqwest",
    "dep:thiserror",
    "dep:sentry-anyhow",
    "dep:parking_lot",
    "dep:ambient_profiling",
    "dep:ring",
    "dep:data-encoding",
    "dep:chrono",
    "dep:bincode",
    "dep:convert_case",
    "dep:once_cell",
    "dep:pin-project",
    "dep:url",
    "dep:relative-path",
    "dep:toml",
    "dep:percent-encoding",
]

# Changes in behaviour
hotload-includes = []
sentry = []
