tests = [
    "basics/async",
    "basics/decals",
    "basics/first_person_camera",
    "basics/fog",
    "basics/image",
    "basics/input",
    "basics/primitives",
    "basics/procedural_generation",
    "basics/raw_text",
    "basics/samplers",
    "basics/third_person_camera",
    "basics/transparency",
    "games/tictactoe",
    "ui/auto_editor",
    "ui/button",
    "ui/dock_layout",
    "ui/editors",
    "ui/flow_layout",
    "ui/image",
    "ui/rect",
    "ui/screens",
    "ui/slider",
    "ui/text",
]
