[project]
id = "procedural_generation"
name = "Procedural generation"
version = "0.0.1"

[components]
rotating_sun = { type = "Bool", name = "Rotating sun", description = "Whether or not rotate the sun automatically" }
