[package]
name = "ambient_wasm"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambient_sys = { path = "../sys" }
ambient_animation = { path = "../animation" }
ambient_app = { path = "../app" }
ambient_core = { path = "../core" }
ambient_ecs = { path = "../ecs" }
ambient_input = { path = "../input" }
ambient_network = { path = "../network" }
ambient_model = { path = "../model" }
ambient_std = { path = "../std" }
ambient_gpu = { path = "../gpu" }
ambient_renderer = { path = "../renderer" }
ambient_procedurals = { path = "../procedurals" }

ambient_project = { path = "../../shared_crates/project" }
ambient_shared_types = { path = "../../shared_crates/shared_types", features = [
    "native",
] }

anyhow = { workspace = true }
async-trait = { workspace = true }
byteorder = { workspace = true }
bytes = { workspace = true }
data-encoding = { workspace = true }
chrono = { workspace = true }
flume = { workspace = true }
fs_extra = { workspace = true }
glam = { workspace = true }
indexmap = { workspace = true }
indoc = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
once_cell = { workspace = true }
parking_lot = { workspace = true }
paste = { workspace = true }
ambient_profiling = { workspace = true }
reqwest = { workspace = true }
serde_bytes = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
slotmap = { workspace = true }
tokio = { workspace = true }
winit = { workspace = true }
wgpu = { workspace = true }
ulid = { workspace = true }
tracing = { workspace = true }
wit-component = { workspace = true }
pollster = { workspace = true }

wasmtime = { workspace = true, optional = true }
wasmtime-wasi = { workspace = true, optional = true }
wasi-common = { workspace = true, optional = true }
wasi-cap-std-sync = { workspace = true, optional = true }
ambient_physics = { path = "../physics", optional = true }
physxx = { path = "../../libs/physxx", optional = true }

# Uses physx
ambient_prefab = { path = "../prefab", optional = true }

[target.'cfg(windows)'.build-dependencies]
tracing = { workspace = true }
dunce = "1.0"

[build-dependencies]
ambient_std = { path = "../std", default-features = false }
wit-bindgen-core = { workspace = true }
wit-bindgen-rust = { workspace = true }

[features]
native = ["wasmtime", "wasmtime-wasi", "wasi-common", "wasi-cap-std-sync"]
physics = ["physxx", "ambient_prefab", "ambient_physics"]
wit = []
