[package]
name = "ambient_project_native"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"
description = "Extensions to `ambient_project` that are only relevant to the host. Host-only."
license = "MIT OR Apache-2.0"
repository = "https://github.com/AmbientRun/Ambient"

[dependencies]
ambient_ecs = { path = "../ecs" , version = "0.3.0-dev" }
ambient_project = { path = "../../shared_crates/project" , version = "0.3.0-dev" }

[dev-dependencies]
paste = { workspace = true }
serde_json = { workspace = true }
ambient_shared_types = { path = "../../shared_crates/shared_types", features = ["native"] }
